# Generated by Django 5.1.5 on 2025-02-03 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('EXPENSE', 'Dépense'), ('INCOME', 'Revenu'), ('LEISURE', 'Loisirs'), ('SAVINGS', 'Épargne')], default='EXPENSE', max_length=20)),
                ('icon', models.CharField(default='bi-cash', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_leisure', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('savings_target', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_finances.budgetcategory')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_finances.monthlybudget')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('target_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_finances.student')),
            ],
        ),
        migrations.CreateModel(
            name='PatrimonySimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('duration_months', models.IntegerField()),
                ('inflation_rate', models.DecimalField(decimal_places=2, default=2.0, max_digits=4)),
                ('investment_return_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=4)),
                ('salary_growth_rate', models.DecimalField(decimal_places=2, default=2.0, max_digits=4)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_finances.student')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyRecurringItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_type', models.CharField(choices=[('INCOME', 'Revenu'), ('EXPENSE', 'Dépense'), ('SAVINGS', 'Épargne')], max_length=10)),
                ('category', models.CharField(choices=[('SALARY', 'Salaire'), ('SCHOLARSHIP', 'Bourse'), ('RENTAL', 'Revenus locatifs'), ('OTHER_INCOME', 'Autres revenus'), ('RENT', 'Loyer'), ('UTILITIES', 'Charges'), ('INSURANCE', 'Assurances'), ('PHONE', 'Téléphone/Internet'), ('TRANSPORT', 'Transport'), ('GROCERIES', 'Courses'), ('LEISURE', 'Loisirs'), ('GYM', 'Salle de sport'), ('LAUNDRY', 'Laverie'), ('SHOPPING', 'Shopping'), ('HEALTH', 'Santé'), ('EMERGENCY', 'Épargne de précaution'), ('INVESTMENT', 'Investissements'), ('PROJECTS', 'Projets')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_finances.student')),
            ],
        ),
        migrations.AddField(
            model_name='monthlybudget',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_finances.student'),
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('investment_type', models.CharField(choices=[('STOCKS', 'Actions'), ('SAVINGS', 'Épargne'), ('CRYPTO', 'Cryptomonnaie'), ('REAL_ESTATE', 'Immobilier'), ('OTHER', 'Autre')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('risk_level', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé')], max_length=10)),
                ('expected_return', models.DecimalField(decimal_places=2, max_digits=5)),
                ('actual_return', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_finances.student')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('period', models.CharField(choices=[('MONTHLY', 'Mensuel'), ('QUARTERLY', 'Trimestriel'), ('YEARLY', 'Annuel')], max_length=10)),
                ('savings_goal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_finances.student')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SALARY', 'Salaire'), ('SCHOLARSHIP', 'Bourse'), ('RENTAL', 'Revenus locatifs'), ('HOUSING_BENEFIT', 'APL/AL'), ('ACTIVITY_BONUS', "Prime d'activité"), ('MOBILITY_AID', 'Aide mobilité jeune'), ('OTHER_INCOME', 'Autres revenus'), ('RENT', 'Loyer'), ('UTILITIES', 'Charges'), ('INSURANCE', 'Assurances'), ('PHONE', 'Téléphone/Internet'), ('TRANSPORT', 'Transport'), ('FOOD', 'Alimentation'), ('LEISURE', 'Loisirs'), ('GYM', 'Salle de sport'), ('LAUNDRY', 'Laverie'), ('SHOPPING', 'Shopping'), ('OTHER', 'Autre'), ('EMERGENCY_FUND', 'Épargne de précaution'), ('INVESTMENT_SAVINGS', 'Épargne investissement'), ('PROJECT_SAVINGS', 'Épargne projet'), ('RETIREMENT_SAVINGS', 'Épargne retraite')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_finances.student')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Revenu'), ('EXPENSE', 'Dépense'), ('SAVINGS', 'Épargne')], max_length=7)),
                ('category', models.CharField(choices=[('SALARY', 'Salaire'), ('SCHOLARSHIP', 'Bourse'), ('RENTAL', 'Revenus locatifs'), ('HOUSING_BENEFIT', 'APL/AL'), ('ACTIVITY_BONUS', "Prime d'activité"), ('MOBILITY_AID', 'Aide mobilité jeune'), ('OTHER_INCOME', 'Autres revenus'), ('RENT', 'Loyer'), ('UTILITIES', 'Charges'), ('INSURANCE', 'Assurances'), ('PHONE', 'Téléphone/Internet'), ('TRANSPORT', 'Transport'), ('FOOD', 'Alimentation'), ('LEISURE', 'Loisirs'), ('GYM', 'Salle de sport'), ('LAUNDRY', 'Laverie'), ('SHOPPING', 'Shopping'), ('OTHER', 'Autre'), ('EMERGENCY_FUND', 'Épargne de précaution'), ('INVESTMENT_SAVINGS', 'Épargne investissement'), ('PROJECT_SAVINGS', 'Épargne projet'), ('RETIREMENT_SAVINGS', 'Épargne retraite')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('MONTHLY', 'Mensuel'), ('ONEOFF', 'Ponctuel')], default='ONEOFF', max_length=10)),
                ('payment_day', models.IntegerField(blank=True, help_text='Jour du mois pour les transactions mensuelles', null=True)),
                ('date', models.DateField(blank=True, help_text='Date uniquement pour les transactions ponctuelles', null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_finances.student')),
            ],
            options={
                'ordering': ['frequency', 'payment_day', '-date'],
            },
        ),
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('transport_type', models.CharField(choices=[('PLANE', 'Avion'), ('TRAIN', 'Train'), ('CAR', 'Voiture'), ('BUS', 'Bus'), ('OTHER', 'Autre')], max_length=10)),
                ('transport_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('accommodation_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activities_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('food_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_costs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_finances.student')),
            ],
        ),
    ]
