# Generated by Django 5.1.5 on 2025-02-04 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('SALARY', 'Salaire'), ('SCHOLARSHIP', 'Bourse'), ('RENTAL', 'Revenus locatifs'), ('HOUSING_BENEFIT', 'APL/AL'), ('ACTIVITY_BONUS', "Prime d'activité"), ('MOBILITY_AID', 'Aide mobilité jeune'), ('OTHER_INCOME', 'Autres revenus'), ('RENT', 'Loyer'), ('UTILITIES', 'Charges'), ('INSURANCE', 'Assurances'), ('PHONE', 'Téléphone/Internet'), ('TRANSPORT', 'Transport'), ('FOOD', 'Alimentation'), ('SPORT', 'Sport'), ('LEISURE', 'Loisirs'), ('GYM', 'Salle de sport'), ('LAUNDRY', 'Laverie'), ('SHOPPING', 'Shopping'), ('OTHER', 'Autre'), ('EMERGENCY_FUND', 'Épargne de précaution'), ('INVESTMENT_SAVINGS', 'Épargne investissement'), ('PROJECT_SAVINGS', 'Épargne projet'), ('RETIREMENT_SAVINGS', 'Épargne retraite')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('SALARY', 'Salaire'), ('SCHOLARSHIP', 'Bourse'), ('RENTAL', 'Revenus locatifs'), ('HOUSING_BENEFIT', 'APL/AL'), ('ACTIVITY_BONUS', "Prime d'activité"), ('MOBILITY_AID', 'Aide mobilité jeune'), ('OTHER_INCOME', 'Autres revenus'), ('RENT', 'Loyer'), ('UTILITIES', 'Charges'), ('INSURANCE', 'Assurances'), ('PHONE', 'Téléphone/Internet'), ('TRANSPORT', 'Transport'), ('FOOD', 'Alimentation'), ('SPORT', 'Sport'), ('LEISURE', 'Loisirs'), ('GYM', 'Salle de sport'), ('LAUNDRY', 'Laverie'), ('SHOPPING', 'Shopping'), ('OTHER', 'Autre'), ('EMERGENCY_FUND', 'Épargne de précaution'), ('INVESTMENT_SAVINGS', 'Épargne investissement'), ('PROJECT_SAVINGS', 'Épargne projet'), ('RETIREMENT_SAVINGS', 'Épargne retraite')], max_length=20),
        ),
        migrations.CreateModel(
            name='PlannedPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('planned_date', models.DateField()),
                ('priority', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Haute')], default='MEDIUM', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_finances.student')),
            ],
            options={
                'ordering': ['planned_date', '-priority'],
            },
        ),
    ]
